# Generated by Django 5.1.7 on 2025-04-17 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.room'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.gradelevel'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schoolclass'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='study_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.studyplan'),
        ),
        migrations.AddField(
            model_name='studyplanentry',
            name='study_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='schedule.studyplan'),
        ),
        migrations.AddField(
            model_name='studyplanentry',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.subject'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.subject'),
        ),
        migrations.AddField(
            model_name='subjecthours',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schoolclass'),
        ),
        migrations.AddField(
            model_name='subjecthours',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('grade', 'letter')},
        ),
        migrations.AlterUniqueTogether(
            name='studyplanentry',
            unique_together={('study_plan', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('school_class', 'weekday', 'lesson_number')},
        ),
        migrations.AlterUniqueTogether(
            name='subjecthours',
            unique_together={('school_class', 'subject')},
        ),
    ]
